import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarLayoutWrapper from "./components/SidebarLayoutWrapper";
import RootProvider from "./providers/RootProvider";
import Drawer from "./components/Drawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider>
          <SidebarLayoutWrapper>
            {children}
            <Drawer />
          </SidebarLayoutWrapper>
        </RootProvider>
      </body>
    </html>
  );
} 
